config/routes.rb
Rails.application.routes.draw do

  resources :teams

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  
  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }

  get 'users/auth/:provider/callback', to: 'sessions#create'

  resources :playlist_items

  resources :video_statistics

  resources :videos

  resources :playlists

  resources :channels do 
    resources :channel_statistics
    resources :videos
  end

  resources :regions do 
    resources :channels
  end

  

  root 'home#index'

end

app/models/channel.rb
class Channel < ActiveRecord::Base
	has_many :channel_statistics, dependent: :destroy
	has_many :playlists, dependent: :destroy
	has_many :videos, dependent: :destroy
	has_many :popularities
	has_many :regions, through: :popularities
	has_many :joins
	has_many :teams, through: :joins
	#has_many :playlist_items, dependent: :destroy

	self.per_page = 20
end

app/controllers/channels_controller.rb
class ChannelsController < ApplicationController
  include HTTParty

  before_action :set_channel, only: [:show, :edit, :update, :destroy]
  #before_action :authenticate_user!

  helper_method :sort_column, :sort_direction
  # GET /channels
  # GET /channels.json
  def index
    #@channels = Channel.order("subscriber_count DESC").page(params[:page])
    @channels = Channel.order(sort_column + ' ' + sort_direction).page(params[:page])
    if params[:update_all] == 'true' 
      ChannelsWorker.perform_async
    end
  end

  # GET /channels/1
  # GET /channels/1.json
  def show
    #@stats = Array.new
    @channel_stats = @channel.channel_statistics
    @re_stats = @channel.regions.first.region_statistics
    #@stats << @channel_stats
=begin    
    @channel.regions.each do |r|
      avg_ch = {title: r.name, created_at: r.channels.collect(&:created_at), video_count: r.channels.collect(&:video_count)}
      @stats << avg_ch
      puts "avg_ch : #{avg_ch}"
    end
    puts "stats : #{@stats}"
=end
    @playlists = @channel.playlists
    @videos = @channel.videos
  end

  # GET /channels/new
  def new
    @channel = Channel.new
  end

  # GET /channels/1/edit
  def edit
  end

  # POST /channels
  # POST /channels.json
  def create
    username = params[:channel][:username]

    if username.present?
      response = HTTParty.get("https://www.googleapis.com/youtube/v3/channels?key=AIzaSyCZT4tgs-exq5My9CaiMmf4N6rQ2WFNzIA&forUsername=#{username.to_s}&part=id")
      #channel_params.permit(:ch_id) = JSON.parse(response.body)["items"][0]["id"]
      #puts "channel_id #{channel_params.permit(:ch_id)}"
      @channel = Channel.new(channel_params.merge(ch_id: JSON.parse(response.body)["items"][0]["id"] ))

=begin      
      url = URI.parse("https://www.googleapis.com/youtube/v3/channels?key=AIzaSyCZT4tgs-exq5My9CaiMmf4N6rQ2WFNzIA&forUsername=kyungsunxoxo&part=id")
      req = Net::HTTP::Get.new(url.to_s)
      res = Net::HTTP.start(url.host, url.port) {|http|
        http.request(req)
      }
      puts res.body
=end   
    else   
      @channel = Channel.new(channel_params)

    end
    

    respond_to do |format|
      if @channel.save
        ChannelsWorker.perform_async(@channel.id)
        
        format.html { redirect_to @channel, notice: 'Channel was successfully created.' }
        format.json { render :show, status: :created, location: @channel }
      else
        format.html { render :new }
        format.json { render json: @channel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /channels/1
  # PATCH/PUT /channels/1.json
  def update
    respond_to do |format|
      if @channel.update(channel_params)
        
        ch = Yt::Channel.new id: @channel.ch_id
        @channel.channel_statistics.create(video_count: ch.video_count, view_count: ch.view_count, comment_count: ch.comment_count, subscriber_count: ch.subscriber_count)

        pls = ch.playlists
        if pls
          pls.each do |pl|
            ch_pl = @channel.playlists.find_or_create_by(pl_id: pl.id)
            ch_pl.update(title: pl.title, description: pl.description, thumbnail_url: pl.thumbnail_url, tags: pl.tags, published_at: pl.published_at)
          end
        end

        format.html { redirect_to @channel, notice: 'Channel was successfully updated.' }
        format.json { render :show, status: :ok, location: @channel }
      else
        format.html { render :edit }
        format.json { render json: @channel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /channels/1
  # DELETE /channels/1.json
  def destroy
    @channel.destroy
    respond_to do |format|
      format.html { redirect_to channels_url, notice: 'Channel was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_channel
      @channel = Channel.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def channel_params
      params.require(:channel).permit(:ch_id, :username, :title, :description, :published_at, :thumbnail_url, :video_count, :view_count, :subscriber_count, :comment_count, :joined, { region_ids: [] }, { team_ids: [] })
    end
    def sort_direction
      %w[asc desc].include?(params[:direction]) ?  params[:direction] : "desc"
    end
    def sort_column
      Channel.column_names.include?(params[:sort]) ? params[:sort] : "subscriber_count"
    end
end

app/helpers/channels_helper.rb
module ChannelsHelper
end

app/views/channels/_channels.html.erb
<%- model_class = Channel -%> 


<table class="table table-striped">
  <thead>
    <tr>
      <th>No.</th>
      <th>Creator</th>
<!--      
      <th style="text-align:right; padding-right:10px; ">Videos</th>
      <th style="text-align:right; padding-right:10px; ">Subscribers</th>
      <th style="text-align:right; padding-right:10px; ">Views</th>
      <th style="text-align:right; padding-right:10px; ">Comments</th>
-->
      <th >Regions</th>
      <th >Teams</th>
      <th style="text-align:right; padding-right:10px; "><%= sortable "video_count", "Videos" %></th>
      <th style="text-align:right; padding-right:10px; "><%= sortable "subscriber_count", "Subscribers" %></th>
      <th style="text-align:right; padding-right:10px; "><%= sortable "view_count", "Views" %></th>
      <!-- <th style="text-align:right; padding-right:10px; "><%= sortable "comment_count", "Comments" %></th> -->
      <!-- <th><%=t '.actions', :default => t("helpers.actions") %></th> -->
    </tr>
  </thead>
  <tbody>
    <% @channels.each_with_index do |channel, i| %>
    <% delta = channel.channel_statistics.offset(1).last %>
    <tr <%= "class=joined" if channel.joined %> onClick=document.location=<%= "'#{channel_path(channel)}'" %>; style="cursor: pointer;">
      <td><%= (@channels.current_page - 1) * @channels.per_page + i + 1 %></td>
      <td>
        <div class="media">
          <div class="media-left pull-left">
            <a href="<%= channel_path(channel) %>">
              <%= image_tag(channel.thumbnail_url, :class => "media-object", :style => "width:64px; height: 64px;") %>
            </a>
          </div>
          <div class="media-body">
            <h4 class="media-heading"><%= channel.title %></h4>
            <p><%= channel.description %></p>
            <%= "From #{channel.published_at.to_date}" if channel.published_at %>
          </div>
        </div>
      </td>
      <td><% channel.regions.each do |r| %><%= "#{r.name} " %><% end %></td>
      <td><% channel.teams.each do |t| %><%= "#{t.name} " %><% end %></td>
      <td style="text-align:right; padding-right:10px; "><%= number_with_delimiter(channel.video_count) if channel.video_count %><%= num_diff(channel.video_count, delta.video_count) if delta %></td>
      <td style="text-align:right; padding-right:10px; "><%= number_with_delimiter(channel.subscriber_count) if channel.subscriber_count %><%= num_diff(channel.subscriber_count, delta.subscriber_count) if delta %></td>
      <td style="text-align:right; padding-right:10px; "><%= number_with_delimiter(channel.view_count) if channel.view_count %><%= num_diff(channel.view_count, delta.view_count) if delta %> <%= link_to 'Destroy', channel, method: :delete, data: { confirm: 'Are you sure?' } if user_signed_in? && current_user.email.include?("jwchae") %></td>
      <!-- <td style="text-align:right; padding-right:10px; "><%= number_with_delimiter(channel.comment_count) if channel.comment_count %><%= num_diff(channel.comment_count, delta.comment_count) if delta %> </td>
    -->
    </tr>
    <% end %>
  </tbody>
</table>
<div class="container text-center">
  <%= will_paginate @channels, renderer: BootstrapPagination::Rails %>
</div>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_channel_path,
            :class => 'btn btn-primary' %>

app/views/channels/_form.html.erb
<%= form_for @channel, :html => { :class => "form-horizontal channel" } do |f| %>

    <% if @channel.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@channel.errors.count, "error") %> prohibited this channel from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @channel.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :username, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :username, :class => 'form-control' %>
    </div>
    <%= error_span(@channel[:username]) %>
  </div>

  <div class="control-group">
    <%= f.label :ch_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :ch_id, :class => 'form-control' %>
    </div>
    <%= error_span(@channel[:ch_id]) %>
  </div>
  <div class="control-group">
    <%= f.label :joined, :class => 'control-label' %>
    <div class="controls">
      <%= f.check_box :joined, :class => 'form-control' %>
    </div>
    <%= error_span(@channel[:joined]) %>
  </div>
  <div class="control-group">
    <%= f.label :title, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :title, :class => 'form-control' %>
    </div>
    <%= error_span(@channel[:title]) %>
  </div>
  <div class="control-group">
    <%= f.label :description, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :description, :class => 'form-control' %>
    </div>
    <%= error_span(@channel[:description]) %>
  </div>
  <div class="control-group">
    <%= f.label :published_at, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :published_at, :class => 'form-control' %>
    </div>
    <%= error_span(@channel[:published_at]) %>
  </div>
  <div class="control-group">
    <%= f.label :thumbnail_url, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :thumbnail_url, :class => 'form-control' %>
    </div>
    <%= error_span(@channel[:thumbnail_url]) %>
  </div>

  <h5>Regions</h5>
  <%= hidden_field_tag "channel[region_ids][]", nil %>
    <% Region.all.each do |r| %>
      <%= check_box_tag "channel[region_ids][]", r.id, @channel.region_ids.include?(r.id), id: dom_id(r)  %>
      <%= label_tag dom_id(r), r.name %>
      <br/>
    <% end %>
  <h5>Team</h5>
  <%= hidden_field_tag "channel[team_ids][]", nil %>
    <% Team.all.each do |r| %>
      <%= check_box_tag "channel[team_ids][]", r.id, @channel.team_ids.include?(r.id), id: dom_id(r)  %>
      <%= label_tag dom_id(r), r.name %>
      <br/>
    <% end %>

  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            channels_path, :class => 'btn btn-default' %>

<% end %>

app/views/channels/edit.html.erb
<%- model_class = Channel -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/channels/index.html.erb
<p class="pull-right">At <%= Time.now.getlocal.strftime("%F %R") %>, refresh every 12hrs</p>
<div class="page-header">
  <h2>Creators Dashboard <small><%= number_with_delimiter(@channels.count) %> channels</small></h2>
</div>
<%= render partial: 'channels/channels'  %>

app/views/channels/new.html.erb
<%- model_class = Channel -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/channels/show.html.erb
<%- model_class = Channel -%>
<p class="pull-right">At <%= Time.now.getlocal.strftime("%F %R") %>, refresh every 12hrs</p>
<div class="page-header">
  <h1><%= @channel.title %></h1>
</div>

  <div class="media">
    <div class="media-left pull-left">
      <a href="#">
        <%= image_tag @channel.thumbnail_url, :class => "media-object" %>
      </a>
    </div>
    <div class="media-body">
      <h4 class="media-heading"><%= @channel.title %></h4>
      <p><%= @channel.description %></p>
        <ul class="list-unstyled">
          <li>소속  <% @channel.teams.each do |t| %><%=  t.name %><% end %></li>
          <li>Since  <%= @channel.published_at.to_date %></li>
          <li>Videos  <%= number_with_delimiter(@channel.video_count) %></li>
          <li>Views  <%= number_with_delimiter(@channel.view_count) %></li>
          <li>Subscribers  <%= number_with_delimiter(@channel.subscriber_count) %></li>
          <li>Views Per Video <%= number_with_delimiter(@channel.view_count / @channel.video_count) %></li>
          <li>Subsribers Per Video <%= number_with_delimiter(@channel.subscriber_count / @channel.video_count) %></li>
          <li>주요 활동 국가  <% @channel.regions.each do |r| %><%=  r.name %><% end %></li>
        </ul>
    </div>
  </div>         
<% if @channel_stats %>
<!--  
<%= line_chart [
            {name: "Videos", data: @channel_stats.group_by_day(:created_at).maximum("video_count")}, 
            {name: "Views", data: @channel_stats.group_by_day(:created_at).maximum("view_count")},
            {name: "Subscribers", data: @channel_stats.group_by_day(:created_at).maximum("subscriber_count")}
              ] %>

-->     
<h3>Stats <small>채널 통계</small></h3>
<h4>Videos <small>비디오 통계</small></h4>
<%= line_chart @channel_stats.group_by_day(:created_at).maximum("video_count"), min: (@channel_stats.pluck(:video_count).min.to_f / 10).round * 10 - 5, max: (@channel_stats.pluck(:video_count).max.to_f / 10).ceil * 10 + 5  %>
<%= #line_chart @stats.map { |stat| {name: stat.title, data: stat.group_by_day(:created_at).maximum("video_count") }} 
%>
<h4>Views <small>조회수 통계</small></h4>
<%= line_chart [{name: "#{@channel.title}", data: @channel_stats.group_by_day(:created_at).maximum("view_count")}, ], min: (@channel_stats.pluck(:view_count).min.to_f / 10).round * 10, max: (@channel_stats.pluck(:view_count).max.to_f / 10).ceil * 10 %>
<h4><small>평균 조회수 통계(Views per video)</small></h4>
<%= line_chart [{ name: "#{@channel.title} 평균" , data: @channel_stats.group_by_day(:created_at).maximum("view_count / video_count")}, {name: "#{@channel.regions.first.name} 평균", data: @re_stats.where(created_at: @channel_stats.first.created_at..@channel_stats.last.created_at).group_by_day("created_at").average("view_count / video_count") }], min: (@channel_stats.pluck("view_count / video_count").min.to_f / 10).round * 10, max: (@channel_stats.pluck("view_count / video_count").max.to_f / 10).ceil * 10 %>
<h4>Subscriber <small>구독자 통계</small></h4>
<%= line_chart @channel_stats.group_by_day(:created_at).maximum("subscriber_count"), min: (@channel_stats.pluck(:subscriber_count).min.to_f / 10).round * 10, max: (@channel_stats.pluck(:subscriber_count).max.to_f / 10).ceil * 10 %>
<h4><small>구독 유치 통계(Subscribers per video)</small></h4>
<%= line_chart [{name: "#{@channel.title} 평균", data: @channel_stats.group_by_day(:created_at).maximum("subscriber_count / video_count")}, {name: "#{@channel.regions.first.name} 평균", data: @re_stats.where(created_at: @channel_stats.first.created_at..@channel_stats.last.created_at).group_by_day("created_at").average("subscriber_count / video_count") }], min: (@channel_stats.pluck("subscriber_count / video_count").min.to_f / 10).round * 10, max: (@channel_stats.pluck("subscriber_count / video_count").max.to_f / 10).ceil * 10 %>


<div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingOne">
      <h4 class="panel-title">
        <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
          Detail <small>통계 상세</small>
        </a>
      </h4>
    </div>
    <div id="collapseOne" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingOne">
      <div class="panel-body">
        <table class="table">
          <tr>
            <th>Date</th>
            <th style="text-align:right; padding-right:10px; ">Video #</th>
            <th style="text-align:right; padding-right:10px; ">View #</th>
            <th style="text-align:right; padding-right:10px; ">Comments #</th>
            <th style="text-align:right; padding-right:10px; ">Subscriber #</th>
          </tr>

        <% delta = @channel_stats.first %>
        <% @channel_stats.each_with_index do |stat, i| %>

          <tr >
            <td><%= stat.created_at.getlocal.strftime("%F %R") %></td>
            <td style="text-align:right; padding-right:10px; "><%= link_to number_with_delimiter(stat.video_count), channel_videos_path(@channel.id) %><%= num_diff(stat.video_count, delta.video_count) if i != 0  %></td>
            <td style="text-align:right; padding-right:10px; "><%= number_with_delimiter(stat.view_count) %><%= num_diff(stat.view_count, delta.view_count) if i != 0  %></td>
            <td style="text-align:right; padding-right:10px; "><%= number_with_delimiter(stat.comment_count) %><%= num_diff(stat.comment_count, delta.comment_count) if i != 0  %></td>
            <td  style="text-align:right; padding-right:10px; "><%= number_with_delimiter(stat.subscriber_count) %><%= num_diff(stat.subscriber_count, delta.subscriber_count) if i != 0  %></td>
          </tr>
        <% delta = stat %>
        <%  end %>
        </table>
      </div>
    </div>
  </div>
</div>
<% end %>
<h3>Playlist </h3>
<% if @playlists %>
  <table class="table">
    <tr>
      <th>Playlist Title</th>
      <th>Description</th>
      <th>Tags</th>
    </tr>
  <%  @playlists.order("published_at DESC").each do |pl| %>
    <tr >
      <td><%= link_to image_tag(pl.thumbnail_url), pl %><br/><%= pl.title %></td>
      <td><%= pl.description %></td>
      <td><%= pl.tags %></td>
    </tr>
  <%  end %>
</table>
<% end %>

<div class="row">
  <div class="col-md-6">
    <h3>Videos <small>최신 5개 비디오</small></h3>
    <% if @videos %>
      <%  @videos.order("published_at DESC").limit(5).each do |v| %>
        <div class="media">
          <div class="media-left pull-left">
            <a href="<%= video_path(v) %>">
              <%= image_tag(v.thumbnail_url, :class => "media-object") %>
            </a>
          </div>
          <div class="media-body">
            <h4 class="media-heading"><%= v.title %></h4>
            <%= v.description %>
            <ul class="list-unstyled">
              <li>Uploaded  <%= v.published_at.to_date %></li>
              <li>Views  <%= number_with_delimiter(v.view_count) %></li>
              <li>Likes  <%= number_with_delimiter(v.like_count) %></li>
              <li>Comments  <%= number_with_delimiter(v.comment_count) %>
            </ul>
          </div>
        </div>
      <%  end %>
    <% end %>
  </div>
  <div class="col-md-6">
    <h3>Videos <small>인기 5개 비디오</small></h3>
    <% if @videos %>
      <%  @videos.order("view_count DESC").limit(5).each do |v| %>
        <div class="media">
          <div class="media-left pull-left">
            <a href="<%= video_path(v) %>">
              <%= image_tag(v.thumbnail_url, :class => "media-object") %>
            </a>
          </div>
          <div class="media-body">
            <h4 class="media-heading"><%= v.title %></h4>
            <%= v.description %>
            <ul class="list-unstyled">
              <li>Uploaded  <%= v.published_at.to_date %></li>
              <li>Views  <%= number_with_delimiter(v.view_count) %></li>
              <li>Likes  <%= number_with_delimiter(v.like_count) %></li>
              <li>Comments  <%= number_with_delimiter(v.comment_count) %>
            </ul>
          </div>
        </div>
      <%  end %>
    <% end %>
  </div>
</div>

<div class="row">
    <ol class="breadcrumb">
      <li><%= link_to t('.back', :default => t("helpers.links.back")),
                  channels_path, :class => 'btn btn-default'  %></li>
      <li> <%= link_to t('.edit', :default => t("helpers.links.edit")),
                  edit_channel_path(@channel), :class => 'btn btn-default' %></li>
    </ol>
</div>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                  channel_path(@channel),
                  :method => 'delete',
                  :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                  :class => 'btn btn-danger' if user_signed_in? && current_user.email.include?("jwchae") %>