config/routes.rb
Rails.application.routes.draw do

  resources :teams

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  
  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }

  get 'users/auth/:provider/callback', to: 'sessions#create'

  resources :playlist_items

  resources :video_statistics

  resources :videos

  resources :playlists

  resources :channels do 
    resources :channel_statistics
    resources :videos
  end

  resources :regions do 
    resources :channels
  end

  

  root 'home#index'

end

app/models/channel.rb
class Channel < ActiveRecord::Base
	has_many :channel_statistics, dependent: :destroy
	has_many :playlists, dependent: :destroy
	has_many :videos, dependent: :destroy
	has_many :popularities
	has_many :regions, through: :popularities
	has_many :joins
	has_many :teams, through: :joins
	#has_many :playlist_items, dependent: :destroy

	self.per_page = 20
end

app/models/channel_statistic.rb
class ChannelStatistic < ActiveRecord::Base
  belongs_to :channel
end

app/models/join.rb
class Join < ActiveRecord::Base
	belongs_to :team
	belongs_to :channel
end

app/models/playlist.rb
class Playlist < ActiveRecord::Base
  belongs_to :channel
  has_many :playlist_items, dependent: :destroy
end

app/models/playlist_item.rb
class PlaylistItem < ActiveRecord::Base
  belongs_to :playlist
  belongs_to :video
  #belongs_to :channel
end

app/models/popularity.rb
class Popularity < ActiveRecord::Base
	belongs_to :channel
	belongs_to :region
end

app/models/region.rb
class Region < ActiveRecord::Base
	has_many :popularities
	has_many :channels, through: :popularities
	has_many :region_statistics, dependent: :destroy
end

app/models/region_statistic.rb
class RegionStatistic < ActiveRecord::Base
	belongs_to :region
end

app/models/team.rb
class Team < ActiveRecord::Base
	has_many :joins
	has_many :channels, through: :joins
	has_many :team_statistics, dependent: :destroy
end

app/models/team_statistic.rb
class TeamStatistic < ActiveRecord::Base
  belongs_to :team
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable, :omniauth_providers => [:google_oauth2]
  

def self.new_with_session(params, session)
	puts "self new with session launched"
  if session["devise.user_attributes"]
  	puts "user attributes saved"
    new(session["devise.user_attributes"], without_protection: true) do |user|

      user.attributes = params
      user.valid?
    end
  else
    super
  end    
end
=begin
def self.from_omniauth(auth)
	puts "self from omniauth launched"

  where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
  	puts "user check #{user}"
    user.provider = auth.provider
    user.uid = auth.uid
    user.email = auth.email
    user.name = auth.info.name
  end
end
=end

	def self.from_omniauth(auth)
	    user = User.where(:provider => auth.provider, :uid => auth.uid).first

	    #Uncomment the section below if you want users to be created if they don't exist
	     unless user
	         user = User.create(name: auth.info.name,
	            email: auth.info.email,
              provider: auth.provider, 
              uid: auth.uid,
	            password: Devise.friendly_token[0,20]
	         )
	     end
      user
	end

def password_required?
  super && provider.blank?
end

end

app/models/video.rb
class Video < ActiveRecord::Base
  belongs_to :channel
  has_one :video_content_detail, dependent: :destroy
  has_many :video_statistics, dependent: :destroy

  self.per_page = 30

end

app/models/video_statistic.rb
class VideoStatistic < ActiveRecord::Base
  belongs_to :video
end

app/controllers/playlist_items_controller.rb
class PlaylistItemsController < ApplicationController
  before_action :set_playlist_item, only: [:show, :edit, :update, :destroy]

  # GET /playlist_items
  # GET /playlist_items.json
  def index
    @playlist_items = PlaylistItem.all
  end

  # GET /playlist_items/1
  # GET /playlist_items/1.json
  def show
  end

  # GET /playlist_items/new
  def new
    @playlist_item = PlaylistItem.new
  end

  # GET /playlist_items/1/edit
  def edit
  end

  # POST /playlist_items
  # POST /playlist_items.json
  def create
    @playlist_item = PlaylistItem.new(playlist_item_params)

    respond_to do |format|
      if @playlist_item.save
        format.html { redirect_to @playlist_item, notice: 'Playlist item was successfully created.' }
        format.json { render :show, status: :created, location: @playlist_item }
      else
        format.html { render :new }
        format.json { render json: @playlist_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /playlist_items/1
  # PATCH/PUT /playlist_items/1.json
  def update
    respond_to do |format|
      if @playlist_item.update(playlist_item_params)
        format.html { redirect_to @playlist_item, notice: 'Playlist item was successfully updated.' }
        format.json { render :show, status: :ok, location: @playlist_item }
      else
        format.html { render :edit }
        format.json { render json: @playlist_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /playlist_items/1
  # DELETE /playlist_items/1.json
  def destroy
    @playlist_item.destroy
    respond_to do |format|
      format.html { redirect_to playlist_items_url, notice: 'Playlist item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_playlist_item
      @playlist_item = PlaylistItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def playlist_item_params
      params.require(:playlist_item).permit(:playlist_id, :video_id, :it_id, :title, :description, :published_at, :thumbnail_url, :position)
    end
end

app/helpers/channels_helper.rb
module ChannelsHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    html = <<-HTML
    <div class="alert alert-error alert-danger"> <button type="button"
    class="close" data-dismiss="alert">x</button>
      #{messages}
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/playlist_items_helper.rb
module PlaylistItemsHelper
end

app/helpers/playlists_helper.rb
module PlaylistsHelper
end

app/helpers/regions_helper.rb
module RegionsHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/playlist_items/_form.html.erb
<%= form_for(@playlist_item) do |f| %>
  <% if @playlist_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@playlist_item.errors.count, "error") %> prohibited this playlist_item from being saved:</h2>

      <ul>
      <% @playlist_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :playlist_id %><br>
    <%= f.text_field :playlist_id %>
  </div>
  <div class="field">
    <%= f.label :video_id %><br>
    <%= f.text_field :video_id %>
  </div>
  <div class="field">
    <%= f.label :it_id %><br>
    <%= f.text_field :it_id %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :published_at %><br>
    <%= f.datetime_select :published_at %>
  </div>
  <div class="field">
    <%= f.label :thumbnail_url %><br>
    <%= f.text_field :thumbnail_url %>
  </div>
  <div class="field">
    <%= f.label :position %><br>
    <%= f.number_field :position %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/playlist_items/edit.html.erb
<h1>Editing playlist_item</h1>

<%= render 'form' %>

<%= link_to 'Show', @playlist_item %> |
<%= link_to 'Back', playlist_items_path %>

app/views/playlist_items/index.html.erb
<h1>Listing playlist_items</h1>

<table>
  <thead>
    <tr>
      <th>Playlist</th>
      <th>Video</th>
      <th>It</th>
      <th>Title</th>
      <th>Description</th>
      <th>Published at</th>
      <th>Thumbnail url</th>
      <th>Position</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @playlist_items.each do |playlist_item| %>
      <tr>
        <td><%= playlist_item.playlist %></td>
        <td><%= playlist_item.video %></td>
        <td><%= playlist_item.it_id %></td>
        <td><%= playlist_item.title %></td>
        <td><%= playlist_item.description %></td>
        <td><%= playlist_item.published_at %></td>
        <td><%= playlist_item.thumbnail_url %></td>
        <td><%= playlist_item.position %></td>
        <td><%= link_to 'Show', playlist_item %></td>
        <td><%= link_to 'Edit', edit_playlist_item_path(playlist_item) %></td>
        <td><%= link_to 'Destroy', playlist_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Playlist item', new_playlist_item_path %>

app/views/playlist_items/new.html.erb
<h1>New playlist_item</h1>

<%= render 'form' %>

<%= link_to 'Back', playlist_items_path %>

app/views/playlist_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Playlist:</strong>
  <%= @playlist_item.playlist %>
</p>

<p>
  <strong>Video:</strong>
  <%= @playlist_item.video %>
</p>

<p>
  <strong>It:</strong>
  <%= @playlist_item.it_id %>
</p>

<p>
  <strong>Title:</strong>
  <%= @playlist_item.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @playlist_item.description %>
</p>

<p>
  <strong>Published at:</strong>
  <%= @playlist_item.published_at %>
</p>

<p>
  <strong>Thumbnail url:</strong>
  <%= @playlist_item.thumbnail_url %>
</p>

<p>
  <strong>Position:</strong>
  <%= @playlist_item.position %>
</p>

<%= link_to 'Edit', edit_playlist_item_path(@playlist_item) %> |
<%= link_to 'Back', playlist_items_path %>