config/routes.rb
Rails.application.routes.draw do

  resources :teams

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  
  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }

  get 'users/auth/:provider/callback', to: 'sessions#create'

  resources :playlist_items

  resources :video_statistics

  resources :videos

  resources :playlists

  resources :channels do 
    resources :channel_statistics
    resources :videos
  end

  resources :regions do 
    resources :channels
  end

  

  root 'home#index'

end

app/models/channel.rb
class Channel < ActiveRecord::Base
	has_many :channel_statistics, dependent: :destroy
	has_many :playlists, dependent: :destroy
	has_many :videos, dependent: :destroy
	has_many :popularities
	has_many :regions, through: :popularities
	has_many :joins
	has_many :teams, through: :joins
	#has_many :playlist_items, dependent: :destroy

	self.per_page = 20
end

app/models/channel_statistic.rb
class ChannelStatistic < ActiveRecord::Base
  belongs_to :channel
end

app/models/join.rb
class Join < ActiveRecord::Base
	belongs_to :team
	belongs_to :channel
end

app/models/playlist.rb
class Playlist < ActiveRecord::Base
  belongs_to :channel
  has_many :playlist_items, dependent: :destroy
end

app/models/playlist_item.rb
class PlaylistItem < ActiveRecord::Base
  belongs_to :playlist
  belongs_to :video
  #belongs_to :channel
end

app/models/popularity.rb
class Popularity < ActiveRecord::Base
	belongs_to :channel
	belongs_to :region
end

app/models/region.rb
class Region < ActiveRecord::Base
	has_many :popularities
	has_many :channels, through: :popularities
	has_many :region_statistics, dependent: :destroy
end

app/models/region_statistic.rb
class RegionStatistic < ActiveRecord::Base
	belongs_to :region
end

app/models/team.rb
class Team < ActiveRecord::Base
	has_many :joins
	has_many :channels, through: :joins
	has_many :team_statistics, dependent: :destroy
end

app/models/team_statistic.rb
class TeamStatistic < ActiveRecord::Base
  belongs_to :team
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable, :omniauth_providers => [:google_oauth2]
  

def self.new_with_session(params, session)
	puts "self new with session launched"
  if session["devise.user_attributes"]
  	puts "user attributes saved"
    new(session["devise.user_attributes"], without_protection: true) do |user|

      user.attributes = params
      user.valid?
    end
  else
    super
  end    
end
=begin
def self.from_omniauth(auth)
	puts "self from omniauth launched"

  where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
  	puts "user check #{user}"
    user.provider = auth.provider
    user.uid = auth.uid
    user.email = auth.email
    user.name = auth.info.name
  end
end
=end

	def self.from_omniauth(auth)
	    user = User.where(:provider => auth.provider, :uid => auth.uid).first

	    #Uncomment the section below if you want users to be created if they don't exist
	     unless user
	         user = User.create(name: auth.info.name,
	            email: auth.info.email,
              provider: auth.provider, 
              uid: auth.uid,
	            password: Devise.friendly_token[0,20]
	         )
	     end
      user
	end

def password_required?
  super && provider.blank?
end

end

app/models/video.rb
class Video < ActiveRecord::Base
  belongs_to :channel
  has_one :video_content_detail, dependent: :destroy
  has_many :video_statistics, dependent: :destroy

  self.per_page = 30

end

app/models/video_statistic.rb
class VideoStatistic < ActiveRecord::Base
  belongs_to :video
end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController
  before_action :set_playlist, only: [:show, :edit, :update, :destroy]
  #before_action :authenticate_user!

  # GET /playlists
  # GET /playlists.json
  def index
    @playlists = Playlist.all
  end

  # GET /playlists/1
  # GET /playlists/1.json
  def show
  end

  # GET /playlists/new
  def new
    @playlist = Playlist.new
  end

  # GET /playlists/1/edit
  def edit
  end

  # POST /playlists
  # POST /playlists.json
  def create
    @playlist = Playlist.new(playlist_params)

    respond_to do |format|
      if @playlist.save
        format.html { redirect_to @playlist, notice: 'Playlist was successfully created.' }
        format.json { render :show, status: :created, location: @playlist }
      else
        format.html { render :new }
        format.json { render json: @playlist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /playlists/1
  # PATCH/PUT /playlists/1.json
  def update
    respond_to do |format|
      if @playlist.update(playlist_params)
        format.html { redirect_to @playlist, notice: 'Playlist was successfully updated.' }
        format.json { render :show, status: :ok, location: @playlist }
      else
        format.html { render :edit }
        format.json { render json: @playlist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /playlists/1
  # DELETE /playlists/1.json
  def destroy
    @playlist.destroy
    respond_to do |format|
      format.html { redirect_to playlists_url, notice: 'Playlist was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_playlist
      @playlist = Playlist.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def playlist_params
      params.require(:playlist).permit(:pl_id, :title, :description, :thumbnail_url, :published_at, :tags, :channel_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def num_diff(num1, num2, display_flag = true)

		if num1 && num2
			ret = (num1 - num2).to_i
		else
			return ""
		end

		if display_flag == true && ret > 0
			return " (+#{number_with_delimiter(ret)})"
		elsif display_flag == true && ret < 0
			return " (#{number_with_delimiter(ret)})"
		end
	end	

	def sortable(column, title = nil)
		title ||= column.titleize
    	css_class = (column == sort_column) ? "current #{sort_direction}" : nil
    	direction = (column == sort_column && sort_direction == "asc") ? "desc" : "asc"
    	link_to title, {:sort => column, :direction => direction}, {:class => css_class}
	end

	def truncate(text, len, tail = '..')
		if text.present?
			unpacked = text.unpack('U*') 
			unpacked.length > len ? unpacked[0..len-1].pack('U*') + tail : text
		end
	end	
end

app/helpers/channels_helper.rb
module ChannelsHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    html = <<-HTML
    <div class="alert alert-error alert-danger"> <button type="button"
    class="close" data-dismiss="alert">x</button>
      #{messages}
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/playlists_helper.rb
module PlaylistsHelper
end

app/helpers/regions_helper.rb
module RegionsHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/playlists/_form.html.erb
<%= form_for @playlist, :html => { :class => "form-horizontal playlist" } do |f| %>

    <% if @playlist.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@playlist.errors.count, "error") %> prohibited this playlist from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @playlist.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :pl_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :pl_id, :class => 'form-control' %>
    </div>
    <%= error_span(@playlist[:pl_id]) %>
  </div>
  <div class="control-group">
    <%= f.label :title, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :title, :class => 'form-control' %>
    </div>
    <%= error_span(@playlist[:title]) %>
  </div>
  <div class="control-group">
    <%= f.label :description, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :description, :class => 'form-control' %>
    </div>
    <%= error_span(@playlist[:description]) %>
  </div>
  <div class="control-group">
    <%= f.label :thumbnail_url, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :thumbnail_url, :class => 'form-control' %>
    </div>
    <%= error_span(@playlist[:thumbnail_url]) %>
  </div>
  <div class="control-group">
    <%= f.label :published_at, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :published_at, :class => 'form-control' %>
    </div>
    <%= error_span(@playlist[:published_at]) %>
  </div>
  <div class="control-group">
    <%= f.label :tags, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :tags, :class => 'form-control' %>
    </div>
    <%= error_span(@playlist[:tags]) %>
  </div>
  <div class="control-group">
    <%= f.label :channel_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :channel_id, :class => 'form-control' %>
    </div>
    <%= error_span(@playlist[:channel_id]) %>
  </div>


  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            playlists_path, :class => 'btn btn-default' %>

<% end %>

app/views/playlists/edit.html.erb
<%- model_class = Playlist -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/playlists/index.html.erb
<%- model_class = Playlist -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:pl_id) %></th>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:thumbnail_url) %></th>
      <th><%= model_class.human_attribute_name(:published_at) %></th>
      <th><%= model_class.human_attribute_name(:tags) %></th>
      <th><%= model_class.human_attribute_name(:channel_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @playlists.each do |playlist| %>
      <tr>
        <td><%= link_to playlist.id, playlist_path(playlist) %></td>
        <td><%= playlist.pl_id %></td>
        <td><%= playlist.title %></td>
        <td><%= playlist.description %></td>
        <td><%= playlist.thumbnail_url %></td>
        <td><%= playlist.published_at %></td>
        <td><%= playlist.tags %></td>
        <td><%= playlist.channel_id %></td>
        <td><%=l playlist.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_playlist_path(playlist), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      playlist_path(playlist),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_playlist_path,
            :class => 'btn btn-primary' %>

app/views/playlists/new.html.erb
<%- model_class = Playlist -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/playlists/show.html.erb
<%- model_class = Playlist -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:pl_id) %>:</strong></dt>
  <dd><%= @playlist.pl_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:title) %>:</strong></dt>
  <dd><%= @playlist.title %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @playlist.description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:thumbnail_url) %>:</strong></dt>
  <dd><%= @playlist.thumbnail_url %></dd>
  <dt><strong><%= model_class.human_attribute_name(:published_at) %>:</strong></dt>
  <dd><%= @playlist.published_at %></dd>
  <dt><strong><%= model_class.human_attribute_name(:tags) %>:</strong></dt>
  <dd><%= @playlist.tags %></dd>
  <dt><strong><%= model_class.human_attribute_name(:channel_id) %>:</strong></dt>
  <dd><%= @playlist.channel_id %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              playlists_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_playlist_path(@playlist), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              playlist_path(@playlist),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>