config/routes.rb
Rails.application.routes.draw do

  resources :teams

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  
  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }

  get 'users/auth/:provider/callback', to: 'sessions#create'

  resources :playlist_items

  resources :video_statistics

  resources :videos

  resources :playlists

  resources :channels do 
    resources :channel_statistics
    resources :videos
  end

  resources :regions do 
    resources :channels
  end

  

  root 'home#index'

end

app/models/channel.rb
class Channel < ActiveRecord::Base
	has_many :channel_statistics, dependent: :destroy
	has_many :playlists, dependent: :destroy
	has_many :videos, dependent: :destroy
	has_many :popularities
	has_many :regions, through: :popularities
	has_many :joins
	has_many :teams, through: :joins
	#has_many :playlist_items, dependent: :destroy

	self.per_page = 20
end

app/models/channel_statistic.rb
class ChannelStatistic < ActiveRecord::Base
  belongs_to :channel
end

app/models/join.rb
class Join < ActiveRecord::Base
	belongs_to :team
	belongs_to :channel
end

app/models/playlist.rb
class Playlist < ActiveRecord::Base
  belongs_to :channel
  has_many :playlist_items, dependent: :destroy
end

app/models/playlist_item.rb
class PlaylistItem < ActiveRecord::Base
  belongs_to :playlist
  belongs_to :video
  #belongs_to :channel
end

app/models/popularity.rb
class Popularity < ActiveRecord::Base
	belongs_to :channel
	belongs_to :region
end

app/models/region.rb
class Region < ActiveRecord::Base
	has_many :popularities
	has_many :channels, through: :popularities
	has_many :region_statistics, dependent: :destroy
end

app/models/region_statistic.rb
class RegionStatistic < ActiveRecord::Base
	belongs_to :region
end

app/models/team.rb
class Team < ActiveRecord::Base
	has_many :joins
	has_many :channels, through: :joins
	has_many :team_statistics, dependent: :destroy
end

app/models/team_statistic.rb
class TeamStatistic < ActiveRecord::Base
  belongs_to :team
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable, :omniauth_providers => [:google_oauth2]
  

def self.new_with_session(params, session)
	puts "self new with session launched"
  if session["devise.user_attributes"]
  	puts "user attributes saved"
    new(session["devise.user_attributes"], without_protection: true) do |user|

      user.attributes = params
      user.valid?
    end
  else
    super
  end    
end
=begin
def self.from_omniauth(auth)
	puts "self from omniauth launched"

  where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
  	puts "user check #{user}"
    user.provider = auth.provider
    user.uid = auth.uid
    user.email = auth.email
    user.name = auth.info.name
  end
end
=end

	def self.from_omniauth(auth)
	    user = User.where(:provider => auth.provider, :uid => auth.uid).first

	    #Uncomment the section below if you want users to be created if they don't exist
	     unless user
	         user = User.create(name: auth.info.name,
	            email: auth.info.email,
              provider: auth.provider, 
              uid: auth.uid,
	            password: Devise.friendly_token[0,20]
	         )
	     end
      user
	end

def password_required?
  super && provider.blank?
end

end

app/models/video.rb
class Video < ActiveRecord::Base
  belongs_to :channel
  has_one :video_content_detail, dependent: :destroy
  has_many :video_statistics, dependent: :destroy

  self.per_page = 30

end

app/models/video_statistic.rb
class VideoStatistic < ActiveRecord::Base
  belongs_to :video
end

app/controllers/regions_controller.rb
class RegionsController < ApplicationController
  before_action :set_region, only: [:show, :edit, :update, :destroy]

  helper_method :sort_column, :sort_direction
  def index
    @regions = Region.all

    #@regions = Region.order(sort_column + ' ' + sort_direction)
    #respond_with(@regions)
    #RegionsWorker.perform_async
  end

  def show
    #respond_with(@region)
    @channels = @region.channels.order(sort_column + ' ' + sort_direction).page(params[:page])
  end

  def new
    @region = Region.new
    #respond_with(@region)
  end

  def edit
  end

  def create
    @region = Region.new(region_params)
    #@region.save
    #respond_with(@region)

    respond_to do |format|
      if @region.save
        
        format.html { redirect_to @region, notice: 'Region was successfully created.' }
        format.json { render :show, status: :created, location: @region }
      else
        format.html { render :new }
        format.json { render json: @region.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @region.update(region_params)
    #respond_with(@region)
  end

  def destroy
    @region.destroy
    respond_to do |format|
      format.html { redirect_to regions_url, notice: 'Region was successfully destroyed.' }
      format.json { head :no_content }
    end
    #respond_with(@region)
  end

  private
    def set_region
      @region = Region.find(params[:id])
    end

    def region_params
      params.require(:region).permit(:code, :name)
    end
	def sort_direction
      %w[asc desc].include?(params[:direction]) ?  params[:direction] : "desc"
    end
    def sort_column
      Channel.column_names.include?(params[:sort]) ? params[:sort] : "subscriber_count"
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def num_diff(num1, num2, display_flag = true)

		if num1 && num2
			ret = (num1 - num2).to_i
		else
			return ""
		end

		if display_flag == true && ret > 0
			return " (+#{number_with_delimiter(ret)})"
		elsif display_flag == true && ret < 0
			return " (#{number_with_delimiter(ret)})"
		end
	end	

	def sortable(column, title = nil)
		title ||= column.titleize
    	css_class = (column == sort_column) ? "current #{sort_direction}" : nil
    	direction = (column == sort_column && sort_direction == "asc") ? "desc" : "asc"
    	link_to title, {:sort => column, :direction => direction}, {:class => css_class}
	end

	def truncate(text, len, tail = '..')
		if text.present?
			unpacked = text.unpack('U*') 
			unpacked.length > len ? unpacked[0..len-1].pack('U*') + tail : text
		end
	end	
end

app/helpers/channels_helper.rb
module ChannelsHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    html = <<-HTML
    <div class="alert alert-error alert-danger"> <button type="button"
    class="close" data-dismiss="alert">x</button>
      #{messages}
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/playlists_helper.rb
module PlaylistsHelper
end

app/helpers/regions_helper.rb
module RegionsHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/regions/_form.html.erb
<%= simple_form_for(@region) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :code %>
    <%= f.input :name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/regions/_regions.html.erb
<table class="table table-striped">
  <thead>
    <tr>
      <th >Region</th>
      <th style="text-align:right; padding-right:10px; ">Channels</th>
      <th style="text-align:right; padding-right:10px; ">Videos</th>
      <th style="text-align:right; padding-right:10px; ">Subscribers</th>
      <th style="text-align:right; padding-right:10px; ">Views</th>
    </tr>
  </thead>

  <tbody>
    <% @regions.each_with_index do |region, i| %>
    <% delta = region.region_statistics.offset(1).last %>
      
      <tr>
        <td><%= link_to "#{region.name} (#{region.code})", region %></td>
        <td style="text-align:right; padding-right:10px; ">
          <%= number_with_delimiter(region.channels.count) %><%= num_diff(region.channel_count, delta.channel_count) if delta %>
        </td>
        <td style="text-align:right; padding-right:10px; ">
          <% total_videos = 0 %>
          <% region.channels.each do |ch| %>
            <% total_videos = total_videos + ch.video_count if ch.video_count.present? %>

          <% end %>
          <%= number_with_delimiter(total_videos) %><%= num_diff(region.video_count, delta.video_count) if delta %>
        </td>
        <td style="text-align:right; padding-right:10px; ">
          <% total_subscribers = 0 %>
          <% region.channels.each do |ch| %>

            <% total_subscribers = total_subscribers + ch.subscriber_count if ch.subscriber_count.present? %>
            
          <% end %>
          <%= number_with_delimiter(total_subscribers) %><%= num_diff(region.subscriber_count, delta.subscriber_count) if delta %>
        </td>
        <td style="text-align:right; padding-right:10px; ">
          <% total_views = 0 %>
          <% region.channels.each do |ch| %>

            <% total_views = total_views + ch.view_count if ch.view_count.present? %>
            
          <% end %>
          <%= number_with_delimiter(total_views) %><%= num_diff(region.view_count, delta.view_count) if delta %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/regions/edit.html.erb
<h1>Editing region</h1>

<%= render 'form' %>

<%= link_to 'Show', @region %> |
<%= link_to 'Back', regions_path %>

app/views/regions/index.html.erb
<h2>Listing regions</h2>

<h4>Subscribers <small>구독자 통계</small></h4>
<%= pie_chart @regions.order("subscriber_count DESC").group(:name).maximum("subscriber_count").first(10) %>
<h4>Videos <small>비디오 조회 통계</small></h4>
<%= pie_chart @regions.order("view_count DESC").group(:name).maximum("view_count").first(10) %>

<%= render partial: 'regions/regions'  %>
<br>

<%= link_to 'New Region', new_region_path %>

app/views/regions/new.html.erb
<h1>New region</h1>

<%= render 'form' %>

<%= link_to 'Back', regions_path %>

app/views/regions/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @region.name %> <small><%= @region.code %></small></h1>

<h3>Stats <small>Top 10 지역 통계</small></h3>

<h4>Subscribers <small>구독자 통계</small></h4>
<%= pie_chart @region.channels.order("subscriber_count DESC").group(:title).maximum("subscriber_count").first(10) %>
<h4>Videos <small>비디오 조회 통계</small></h4>
<%= pie_chart @region.channels.order("view_count DESC").group(:title).maximum("view_count").first(10) %>

<h3>Subscribers <small>구독자 통계</small></h4>
<h4>Monthly <small>월별 누적</small></h4>
<%= line_chart @region.region_statistics.group_by_month(:created_at).maximum("subscriber_count") %>
<h4>Weekly <small>주별 누적</small></h4>
<%= line_chart @region.region_statistics.group_by_week(:created_at).maximum("subscriber_count") %> <!-- , min: (@team.region_statistics.pluck(:subscriber_count).min.to_f / 10).round * 10 - 5, max: (@team.region_statistics.pluck(:subscriber_count).max.to_f / 10).ceil * 10 + 5  %> -->
<h3>Views <small>조회수 통계</small></h4>
<h4>Monthly <small>월별 누적</small></h4>
<%= line_chart @region.region_statistics.group_by_month(:created_at).maximum("view_count") %> 
<h4>Weekly <small>주별 누적</small></h4>
<%= line_chart @region.region_statistics.group_by_week(:created_at).maximum("view_count") %> <!--, min: (@region.region_statistics.pluck(:view_count).min.to_f / 10).round * 10 - 5, max: (@region.region_statistics.pluck(:view_count).max.to_f / 10).ceil * 10 + 5  %> -->

<%= render partial: 'channels/channels'  %>
<%= link_to 'Edit', edit_region_path(@region) %> |
<%= link_to 'Back', regions_path %>